#!/bin/bash
#
#
# ▄▄▄ .• ▌ ▄ ·. • ▌ ▄ ·.  ▄▄▄·
# ▀▄.▀··██ ▐███▪·██ ▐███▪▐█ ▀█
# ▐▀▀▪▄▐█ ▌▐▌▐█·▐█ ▌▐▌▐█·▄█▀▀█
# ▐█▄▄▌██ ██▌▐█▌██ ██▌▐█▌▐█ ▪▐▌
#  ▀▀▀ ▀▀  █▪▀▀▀▀▀  █▪▀▀▀ ▀  ▀
#
# © 2021-2026 Emma Campbell
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject
# to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

export DOTFILES="$HOME/.dotfiles"

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

DEFAULT_USER="$(whoami)"

# source any language specific configurations
# and files. namely things like node, java, dotnet
# ect
source ~/.node
source ~/.java
source ~/.python

if [[ -e ~/.terraform ]]; then
  source ~/.terraform
fi

if [[ -e ~/.rust ]]; then
  source ~/.rust
  source "$HOME/.cargo/env"
fi

if [[ -e ~/.ruby ]]; then
  source ~/.ruby
fi

if [[ -e ~/.dotnet.conf ]]; then 
  source ~/.dotnet.conf
fi

if [[ -e ~/.docker.conf ]]; then
  source ~/.docker.conf
fi

source ~/.aliases

if [[ -e ~/.localrc ]]; then
  source ~/.localrc
fi

source ~/.paths
source "$HOME/.prompt"

if [[ -e ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi

# "import" our utility methods
if [[ -d ~/.func ]]; then
  local files=("${(@f)$(find -L ~/.func -iname "*.sh")}")
  for f in "${files[@]}"; do
    source "$f"
  done
fi

eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ "$TERM_PROGRAM" == "ghostty" ]]; then
  export TERM=xterm-256color
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


